title: Oak Studio
description: Bartlesville's Branding Agency
root: //oakstudio.co
default_image: /img/desk.jpg
logo: /img/logos/logo_dark_cropped.png
netlify_site_id: 2112d40a-630d-4469-81a4-4e28af97a843
author:
  name: Braden East,
  email: braden@oakstuio.co,
  url: //bradeneast.com
