name: Oak Studio
root: https://oakstudio.co
repo: bradeneast/oakstudio.co
twitter: oakstudioco
year: 2022
status_badge_url: https://api.netlify.com/api/v1/badges/2112d40a-630d-4469-81a4-4e28af97a843/deploy-status
cloud_name: oakstudio
cloud_key: 768884531445911