[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[build]
command = "npm run prebuild && curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume/ci.js --location=https://dreamy-noyce-6c21ca.netlify.app/"
publish = "_site"

[dev]
autoLaunch = true
command = "npm run prebuild && lume --serve"
framework = "#custom"
port = 8888
publish = "_site"
targetPort = 3000
