[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
  '**/404/*',
]

[[redirects]]
from = "/*"
status = 404
to = "/404/"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
