[dev]
autoLaunch = true
command = "lume --serve"
framework = "#custom"
port = 8888
publish = "_site"
targetPort = 3000

# Admin invitation email templates need to be declared under `Site settings > Identity > Emails` in the Netlify UI
