[build]
command = "npm run prebuild && curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume/ci.ts --location=https://oakstudio.co/"
publish = "_site"

[dev]
autoLaunch = true
command = "lume --serve"
framework = "#custom"
port = 8888
publish = "_site"
targetPort = 3000

[[redirects]]
from = "/projects"
status = 301
to = "/work"

[[redirects]]
from = "/*"
status = 404
to = "/404"

[[redirects]]
force = true
from = "https://oakstudio.netlify.app"
status = 301
to = "https://oakstudio.co"
